In [1]:
# from pymoo.algorithms.soo.nonconvex.ga import GA
# from pymoo.optimize import minimize
# from pymoo.core.problem import ElementwiseProblem
# class MyProblem(ElementwiseProblem):
#     def __init__(self):
#         super().__init__(n_var=2, n_obj=1, xl=0, xu=5)

#     def _evaluate(self, x, out, *args, **kwargs):
#         f1 = (x[0] - 2)**2 + (x[1] - 3)**2
#         out["F"] = f1

# problem = MyProblem()
# algorithm = GA(pop_size=50)
# res = minimize(problem,
#                algorithm,
#                ('n_gen', 40),
#                verbose=False)
# print("Best solution found: \nX = %s\nF = %s" % (res.X, res.F))

Evaluate using NSGA

In [2]:
# from pymoo.algorithms.moo.nsga2 import NSGA2
# from pymoo.optimize import minimize
# from pymoo.core.problem import ElementwiseProblem

In [3]:
# # Define the custom problem
# class MyProblem(ElementwiseProblem):
#     def __init__(self):
#         super().__init__(n_var=2, n_obj=2, xl=-10, xu=10)

#     def _evaluate(self, x, out, *args, **kwargs):
#         f1 = (x[0]**2 + x[0] * x[1] - 6)**2
#         f2 = (x[0]**2 + x[1]**3 + 2 * x[0] * x[1] - 3)**2
#         out["F"] = [f1, f2]

# problem = MyProblem()

In [4]:
# # Choose NSGA-II as the method for the multi-objective problem
# algorithm = NSGA2(pop_size=100)

# # Perform the optimization
# res = minimize(problem,
#                algorithm,
#                ('n_gen', 100),
#                verbose=True)

In [5]:
# # Print the best solution(s)
# print('Best solution(s):')
# for solution in res.X:
#     print(f"X = {solution}, F = {problem.evaluate(solution)}")

Evaluate using GA

In [2]:
from pymoo.algorithms.soo.nonconvex.ga import GA
from pymoo.optimize import minimize
from pymoo.core.problem import ElementwiseProblem
from pymoo.termination.ftol import SingleObjectiveSpaceTermination
from pymoo.termination.robust import RobustTermination
from pymoo.termination.default import DefaultSingleObjectiveTermination
from pymoo.operators.mutation.pm import PolynomialMutation

In [3]:
class Mastorakis1Problem(ElementwiseProblem):
    def __init__(self):
        super().__init__(n_var=2,n_obj=1,xl=-10,xu=10)
    def _evaluate(self, x, out, *args, **kwargs):
        f1 = (x[0]**2+x[0]*x[1]-6)**2+(x[0]**2+x[1]**3+2*x[0]*x[1]**2-3)**2
        out['F'] = f1

m1problem = Mastorakis1Problem()

In [4]:
# GA parameter
mutation = PolynomialMutation(prob=0.2)
algorithmGA = GA(pop_size=40,eliminate_duplicates=True,mutation=mutation)

# termination variable
termination1 = RobustTermination(
    SingleObjectiveSpaceTermination(tol=0.005, n_skip=5), period=20)
termination2 = DefaultSingleObjectiveTermination(
    xtol=1e-8,
    cvtol=1e-6,
    ftol=1e-6,
    period=20,
    n_max_gen=100,
    n_max_evals=100000
)

m1res = minimize(problem=m1problem,
                 algorithm=algorithmGA,
                 termination=termination2,
                 seed=None,
                 verbose=True)

print("Best solution found: \nX = %s\nF = %s" % (m1res.X, m1res.F))

n_gen  |  n_eval  |     f_avg     |     f_min    
     1 |       40 |  1.810172E+05 |  9.1670030667
     2 |       80 |  1.173919E+03 |  9.1670030667
     3 |      120 |  1.020086E+02 |  8.4964770965
     4 |      160 |  3.140033E+01 |  8.4964770965
     5 |      200 |  1.922185E+01 |  8.4964770965
     6 |      240 |  1.293692E+01 |  5.9157192832
     7 |      280 |  9.9917298908 |  5.6535981554
     8 |      320 |  7.9219625474 |  1.3567051501
     9 |      360 |  5.8264886930 |  1.3567051501
    10 |      400 |  4.7032252852 |  0.9577549711
    11 |      440 |  3.9862932346 |  0.3155322741
    12 |      480 |  2.9406524434 |  0.0383897421
    13 |      520 |  1.4914122128 |  0.0383897421
    14 |      560 |  0.4956157528 |  0.0383897421
    15 |      600 |  0.2364293079 |  0.0382379478
    16 |      640 |  0.1122482838 |  0.0379614626
    17 |      680 |  0.0457540781 |  0.0345873983
    18 |      720 |  0.0378144545 |  0.0345873983
    19 |      760 |  0.0367672684 |  0.0324391534


# Root GA

In [1]:
from pymoo.algorithms.soo.nonconvex.ga import GA
from pymoo.optimize import minimize
from pymoo.core.problem import ElementwiseProblem
from pymoo.termination.default import DefaultSingleObjectiveTermination
from pymoo.operators.mutation.pm import PolynomialMutation
import numpy as np
from itertools import product,combinations
import matplotlib.pyplot as plt

Problem 1 Paper Pak Kun

In [10]:
# epsilon = 10**(-3)
# delta = 0.01
# n_point = 100
# gen_max = 300
# dim = 2
# p_mutation = 0.1

# # how many parts/slices do you desire in each dimension?
# parts = 100

# def objective_function(x):
#     f1 = np.exp(x[0]-x[1])-np.sin(x[0]+x[1])
#     f2 = (x[0]*x[1])**2-np.cos(x[0]+x[1])
#     return np.array([f1,f2])

# boundaries = np.array([(-10,10) for _ in range (dim)])

Problem 2 Pak Kun

In [2]:
m_cluster = 50
gamma = 0.3
epsilon = 10**(-3)
delta = 0.1
n_point = 50
gen_max = 300
dim = 2
p_mutation = 0.1

# how many parts/slices do you desire in each dimension?
parts = 25

def objective_function(x):
    f1 = 0.5*np.sin(x[0]*x[1])-0.25*x[1]/np.pi - 0.5*x[0]
    f2 = (1-0.25/np.pi)*(np.exp(2*x[0])-np.exp(1))+np.exp(1)*x[1]/np.pi - 2*np.exp(1)*x[0]
    return np.array([f1,f2])

boundaries = np.array([[-1,3],[-17,4]])

Problem 5 Pak Kun

In [12]:
# m_cluster = 100
# gamma = 0.1
# epsilon = 5*10**(-3)
# delta = 0.01
# gen_max = 200
# dim = 5
# p_mutation = 0.1
# parts = 40

# def objective_function(x):
#     f1 = 2*x[0]+x[1]+x[2]+x[3]+x[4]-6
#     f2 = x[0]+2*x[1]+x[2]+x[3]+x[4]-6
#     f3 = x[0]+x[1]+2*x[2]+x[3]+x[4]-6
#     f4 = x[0]+x[1]+x[2]+2*x[3]+x[4]-6
#     f5 = x[0]*x[1]*x[2]*x[3]*x[4]-1
#     return np.array([f1,f2,f3,f4,f5])

# boundaries = np.array([(-10,10) for _ in range (dim)])

# Root Objective Function Transformator

## Mastorakis' Cluster

In [3]:
def root_objective_function(x:np.ndarray):
    F_array = objective_function(x)
    denom = 0
    for f in F_array:
        denom +=np.abs(f)
    F = 1/(1+denom)
    return -F

In [4]:
def slice_hypercube(lower_bounds, upper_bounds, interval, dim):
    # Create a list of arrays, each containing points spaced h apart for each dimension
    points = [np.arange(lower_bounds[i], upper_bounds[i], interval) for i in range(dim)]
    
    # Use meshgrid to create a grid of points in n-dimensional space
    grids = np.meshgrid(*points, indexing='ij')
    
    # Flatten and combine the grid points into a single 2D array
    grid_points = np.vstack([grid.ravel() for grid in grids]).T
    
    # Generate all vertices for smaller hypercubes within each grid cell
    return np.array([grid_points + offset for offset in product([0, interval], repeat=dim)])

In [5]:
# length of each parts in each dimension
inc_int = (boundaries[0,1]-boundaries[0,0])/parts

# Hypercubes
hypercubes_edges = slice_hypercube(lower_bounds=boundaries[:,0],
                    upper_bounds=boundaries[:,1],
                    interval=inc_int,
                    dim=dim)

In [6]:
cluster = []
for hypercube_id in range(hypercubes_edges.shape[1]):
    X0 = hypercubes_edges[:,hypercube_id,:]
    F_list = objective_function(X0.T)

    # cek jika f yang berubah tanda dari F_list jika dievaluasi di tiap edge hypercube
    product_combination = np.array([[a*b for a,b in combinations(F_list[i],2)] for i in range (F_list.shape[0])])

    # jika semua f dari F_list berubah tanda jika dievaluasi di tiap edge hypercube, maka ada akar di situ
    change_sign = np.array([np.any(product_combination[i]<0) for i in range (product_combination.shape[0])])
    if np.all(change_sign==True):
        # print(f'Ada akar di sini: \nX0={X0}')
        cluster.append(X0)

cluster = np.array(cluster)
print(f"Number of clusters containing root: {cluster.shape[0]}")

Number of clusters containing root: 56


In [7]:
# GA parameter
mutation = PolynomialMutation(prob=p_mutation)
algorithmGAp1 = GA(pop_size=n_point,eliminate_duplicates=True,mutation=mutation)

# termination variable
terminationp1 = DefaultSingleObjectiveTermination(
    xtol=1e-8,
    cvtol=1e-6,
    ftol=1e-6,
    period=20,
    n_max_gen=gen_max,
    n_max_evals=100000
)

def GenAl(n_var,n_obj,xl,xu,objective_function,algorithmGA,termination,seed=1,verbose=False):
    class myProblem(ElementwiseProblem):
        def __init__(self):
            super().__init__(n_var=n_var,n_obj=n_obj,xl=xl,xu=xu)
        def _evaluate(self, x, out, *args, **kwargs):
            out['F'] = objective_function(x)

    problem = myProblem()
    result = minimize(problem=problem,
                    algorithm=algorithmGA,
                    termination=termination,
                    seed=seed,
                    verbose=verbose)
    return [result.X,result.F]

roots = []
values = []
for i in range (cluster.shape[0]):
    root,value = GenAl(2,1,xl=cluster[i,:,:][0],xu=cluster[i,:,:][-1],objective_function=root_objective_function,
                        algorithmGA=algorithmGAp1,termination=terminationp1,seed=0)
    roots.append(root)
    values.append(value)
roots = np.array(roots)
values = np.array(values)
print(f'Roots:\n{roots}\n\nValues: \n{values}')

Roots:
[[ -0.26760389   0.58730717]
 [ -0.26206723   0.61515932]
 [  0.30068372   2.83989935]
 [  0.30200021   2.84305228]
 [  0.43878478   3.09017169]
 [  0.50018091   3.14170707]
 [  1.35255374  -4.52      ]
 [  1.34669312  -4.3708364 ]
 [  1.34168377  -4.24569563]
 [  1.33736683  -4.13899354]
 [  1.33331361  -4.03985546]
 [  1.32663129  -3.87860695]
 [  1.29439648  -3.13798876]
 [  1.2912437   -3.06880349]
 [  1.54852909 -10.92257825]
 [  1.54604567 -10.82154028]
 [  1.54054372 -10.6       ]
 [  1.53651411 -10.44      ]
 [  1.53250295 -10.28055855]
 [  1.53050383 -10.20218989]
 [  1.52822781 -10.11444597]
 [  1.4943378   -8.84474909]
 [  1.48998977  -8.6888336 ]
 [  1.48534007  -8.52451588]
 [  1.48196602  -8.40581901]
 [  1.48057376  -8.35762026]
 [  1.47593789  -8.1970885 ]
 [  1.47131254  -8.03864228]
 [  1.4665305   -7.87665535]
 [  1.43712189  -6.92000221]
 [  1.43386023  -6.81798903]
 [  1.43167366  -6.75048607]
 [  1.42642308  -6.58840702]
 [  1.42120405  -6.42995939]
 [  1.6

In [8]:
if dim == 1:
    list_criteria = [element for sublist in roots for element in sublist] #convert from 2D array into 1D array
else:
    list_criteria = roots
eligible_roots = np.array([x for x in list_criteria if (1-root_objective_function(x))<epsilon])
duplicated_roots = []
for i in range(len(eligible_roots)):
    for j in range (i+1,len(eligible_roots)):
        if np.linalg.norm(eligible_roots[i]-eligible_roots[j])<delta:
            duplicated_roots.append([eligible_roots[i],eligible_roots[j]])
duplicated_roots = np.unique(duplicated_roots,axis=0)

deselected_duplicated_roots = []
for i in range (len(duplicated_roots)):
    value_root_a = root_objective_function(duplicated_roots[i][0])
    value_root_b = root_objective_function(duplicated_roots[i][1])
    if dim == 1:
        if value_root_a>value_root_b:
            duplicated_root = duplicated_roots[i][1]
        else:
            duplicated_root = duplicated_roots[i][0]
    else:
        if value_root_a>value_root_b:
            duplicated_root = list(duplicated_roots[i][1])
        else:
            duplicated_root = list(duplicated_roots[i][0])
    deselected_duplicated_roots.append(duplicated_root)

if dim == 1:
    # Reshape the 1D array to have one column
    deselected_duplicated_roots = np.array(deselected_duplicated_roots).reshape(-1, 1)

    # Compare the 2D array with the reshaped 1D array
    exclude_condition = np.all(eligible_roots != deselected_duplicated_roots, axis=0)

    # Use the boolean mask to filter eligible_roots
    final_root = eligible_roots[exclude_condition]
else:
    if deselected_duplicated_roots:
        exclude_condition = np.all(eligible_roots != np.array(deselected_duplicated_roots)[:, np.newaxis], axis=2).all(axis=0)
        final_root = eligible_roots[exclude_condition]
    else:
        final_root = eligible_roots

print(f'Final Roots: \n{final_root}')

Final Roots: 
[]


### Automatic Function

In [4]:
import genal_module as gam
import numpy as np
import matplotlib.pyplot as plt
import importlib
importlib.reload(gam)

epsilon = 10**(-3)
delta = 0.4
n_point = 50
gen_max = 100
dim = 2
p_mutation = 0.1

# how many parts/slices do you desire in each dimension?
parts = 25

def objective_function(x):
    f1 = 0.5*np.sin(x[0]*x[1])-0.25*x[1]/np.pi - 0.5*x[0]
    f2 = (1-0.25/np.pi)*(np.exp(2*x[0])-np.exp(1))+np.exp(1)*x[1]/np.pi - 2*np.exp(1)*x[0]
    return np.array([f1,f2])

def root_objective_function(x:np.ndarray):
    F_array = objective_function(x)
    denom = 0
    for f in F_array:
        denom +=np.abs(f)
    F = 1/(1+denom)
    return -F

boundaries = np.array([(-1,3),(-17,4)])

roots = gam.root_GenAl(objective_function=objective_function,
                        root_objective_function=root_objective_function,
                        boundaries=boundaries,
                        dim=dim,
                        gen_max=gen_max,
                        n_points=n_point,
                        epsilon=epsilon,
                        delta=delta,
                        p_mutation=p_mutation,
                        parts=parts,
                        seed=0,
                        print_cluster=True)
roots

Number of Clusters containing root: 56

Roots:
[[ -0.26760403   0.58730659]
 [ -0.26206721   0.61515792]
 [  0.30068372   2.83989935]
 [  0.30200024   2.84309029]
 [  0.43878469   3.09017173]
 [  0.50018092   3.14170707]
 [  1.35255374  -4.52000019]
 [  1.34669312  -4.37083611]
 [  1.34168378  -4.2456955 ]
 [  1.3381202   -4.15753163]
 [  1.33331361  -4.03985546]
 [  1.32663129  -3.87860695]
 [  1.29439649  -3.13795638]
 [  1.2912437   -3.06880349]
 [  1.54852909 -10.92229025]
 [  1.54617273 -10.82656122]
 [  1.54054371 -10.60000108]
 [  1.53651411 -10.44000001]
 [  1.53241822 -10.2800001 ]
 [  1.53050383 -10.20219001]
 [  1.52822781 -10.11501707]
 [  1.4943378   -8.84474879]
 [  1.48998978  -8.68883326]
 [  1.48637261  -8.55983262]
 [  1.48196602  -8.40581901]
 [  1.48057376  -8.35816911]
 [  1.47593789  -8.19753378]
 [  1.47131254  -8.03864228]
 [  1.4665305   -7.87665535]
 [  1.43712189  -6.92000213]
 [  1.43386023  -6.81798903]
 [  1.43167366  -6.75118336]
 [  1.42642308  -6.588407

array([[ -0.26206721,   0.61515792],
       [  0.50018092,   3.14170707],
       [  1.3381202 ,  -4.15753163],
       [  1.29439649,  -3.13795638],
       [  1.53050383, -10.20219001],
       [  1.48196602,  -8.40581901],
       [  1.43386023,  -6.81798903],
       [  1.65411895, -15.79513334],
       [  1.60457451, -13.36293482],
       [  1.57834851, -12.18244754]])