In [1]:
# from pymoo.algorithms.soo.nonconvex.ga import GA
# from pymoo.optimize import minimize
# from pymoo.core.problem import ElementwiseProblem
# class MyProblem(ElementwiseProblem):
#     def __init__(self):
#         super().__init__(n_var=2, n_obj=1, xl=0, xu=5)

#     def _evaluate(self, x, out, *args, **kwargs):
#         f1 = (x[0] - 2)**2 + (x[1] - 3)**2
#         out["F"] = f1

# problem = MyProblem()
# algorithm = GA(pop_size=50)
# res = minimize(problem,
#                algorithm,
#                ('n_gen', 40),
#                verbose=False)
# print("Best solution found: \nX = %s\nF = %s" % (res.X, res.F))

Evaluate using NSGA

In [2]:
# from pymoo.algorithms.moo.nsga2 import NSGA2
# from pymoo.optimize import minimize
# from pymoo.core.problem import ElementwiseProblem

In [3]:
# # Define the custom problem
# class MyProblem(ElementwiseProblem):
#     def __init__(self):
#         super().__init__(n_var=2, n_obj=2, xl=-10, xu=10)

#     def _evaluate(self, x, out, *args, **kwargs):
#         f1 = (x[0]**2 + x[0] * x[1] - 6)**2
#         f2 = (x[0]**2 + x[1]**3 + 2 * x[0] * x[1] - 3)**2
#         out["F"] = [f1, f2]

# problem = MyProblem()

In [4]:
# # Choose NSGA-II as the method for the multi-objective problem
# algorithm = NSGA2(pop_size=100)

# # Perform the optimization
# res = minimize(problem,
#                algorithm,
#                ('n_gen', 100),
#                verbose=True)

In [5]:
# # Print the best solution(s)
# print('Best solution(s):')
# for solution in res.X:
#     print(f"X = {solution}, F = {problem.evaluate(solution)}")

Evaluate using GA

In [6]:
# from pymoo.algorithms.soo.nonconvex.ga import GA
# from pymoo.optimize import minimize
# from pymoo.core.problem import ElementwiseProblem
# from pymoo.termination.ftol import SingleObjectiveSpaceTermination
# from pymoo.termination.robust import RobustTermination
# from pymoo.termination.default import DefaultSingleObjectiveTermination
# from pymoo.operators.mutation.pm import PolynomialMutation

In [7]:
# class Mastorakis1Problem(ElementwiseProblem):
#     def __init__(self):
#         super().__init__(n_var=2,n_obj=1,xl=-10,xu=10)
#     def _evaluate(self, x, out, *args, **kwargs):
#         f1 = (x[0]**2+x[0]*x[1]-6)**2+(x[0]**2+x[1]**3+2*x[0]*x[1]**2-3)**2
#         out['F'] = f1

# m1problem = Mastorakis1Problem()

In [8]:
# # GA parameter
# mutation = PolynomialMutation(prob=0.2)
# algorithmGA = GA(pop_size=40,eliminate_duplicates=True,mutation=mutation)

# # termination variable
# termination1 = RobustTermination(
#     SingleObjectiveSpaceTermination(tol=0.005, n_skip=5), period=20)
# termination2 = DefaultSingleObjectiveTermination(
#     xtol=1e-8,
#     cvtol=1e-6,
#     ftol=1e-6,
#     period=20,
#     n_max_gen=100,
#     n_max_evals=100000
# )

# m1res = minimize(problem=m1problem,
#                  algorithm=algorithmGA,
#                  termination=termination2,
#                  seed=None,
#                  verbose=True)

# print("Best solution found: \nX = %s\nF = %s" % (m1res.X, m1res.F))

# Root GA

In [2]:
from pymoo.algorithms.soo.nonconvex.ga import GA
from pymoo.optimize import minimize
from pymoo.core.problem import ElementwiseProblem
from pymoo.termination.default import DefaultSingleObjectiveTermination
from pymoo.operators.mutation.pm import PolynomialMutation
import numpy as np
from itertools import product,combinations
import matplotlib.pyplot as plt

Problem 1 Paper Pak Kun

In [3]:
epsilon = 10**(-3)
delta = 0.01
n_point = 100
gen_max = 300
dim = 2
p_mutation = 0.1

# how many parts/slices do you desire in each dimension?
parts = 100

def objective_function(x):
    f1 = np.exp(x[0]-x[1])-np.sin(x[0]+x[1])
    f2 = (x[0]*x[1])**2-np.cos(x[0]+x[1])
    return np.array([f1,f2])

boundaries = np.array([(-10,10) for _ in range (dim)])

Problem 2 Pak Kun

In [11]:
# m_cluster = 50
# gamma = 0.3
# epsilon = 10**(-3)
# delta = 0.1
# n_point = 100
# gen_max = 300
# dim = 2
# p_mutation = 0.1

# # how many parts/slices do you desire in each dimension?
# parts = 100

# def objective_function(x):
#     f1 = 0.5*np.sin(x[0]*x[1])-0.25*x[1]/np.pi - 0.5*x[0]
#     f2 = (1-0.25/np.pi)*(np.exp(2*x[0])-np.exp(1))+np.exp(1)*x[1]/np.pi - 2*np.exp(1)*x[0]
#     return np.array([f1,f2])

# boundaries = np.array([[-1,3],[-17,4]])

Problem 5 Pak Kun

In [12]:
# m_cluster = 100
# gamma = 0.1
# epsilon = 5*10**(-3)
# delta = 0.01
# gen_max = 200
# dim = 5
# p_mutation = 0.1
# parts = 40

# def objective_function(x):
#     f1 = 2*x[0]+x[1]+x[2]+x[3]+x[4]-6
#     f2 = x[0]+2*x[1]+x[2]+x[3]+x[4]-6
#     f3 = x[0]+x[1]+2*x[2]+x[3]+x[4]-6
#     f4 = x[0]+x[1]+x[2]+2*x[3]+x[4]-6
#     f5 = x[0]*x[1]*x[2]*x[3]*x[4]-1
#     return np.array([f1,f2,f3,f4,f5])

# boundaries = np.array([(-10,10) for _ in range (dim)])

# Root Objective Function Transformator

## Mastorakis' Cluster

In [13]:
def root_objective_function(x:np.ndarray):
    F_array = objective_function(x)
    denom = 0
    for f in F_array:
        denom +=np.abs(f)
    F = 1/(1+denom)
    return F

In [14]:
def slice_hypercube(lower_bounds, upper_bounds, interval, dim):
    # Create a list of arrays, each containing points spaced h apart for each dimension
    points = [np.arange(lower_bounds[i], upper_bounds[i], interval) for i in range(dim)]
    
    # Use meshgrid to create a grid of points in n-dimensional space
    grids = np.meshgrid(*points, indexing='ij')
    
    # Flatten and combine the grid points into a single 2D array
    grid_points = np.vstack([grid.ravel() for grid in grids]).T
    
    # Generate all vertices for smaller hypercubes within each grid cell
    return np.array([grid_points + offset for offset in product([0, interval], repeat=dim)])

In [15]:
# length of each parts in each dimension
inc_int = (boundaries[0,1]-boundaries[0,0])/parts

# Hypercubes
hypercubes_edges = slice_hypercube(lower_bounds=boundaries[:,0],
                    upper_bounds=boundaries[:,1],
                    interval=inc_int,
                    dim=dim)

In [16]:
cluster = []
for hypercube_id in range(hypercubes_edges.shape[1]):
    X0 = hypercubes_edges[:,hypercube_id,:]
    F_list = objective_function(X0.T)

    # cek jika f yang berubah tanda dari F_list jika dievaluasi di tiap edge hypercube
    product_combination = np.array([[a*b for a,b in combinations(F_list[i],2)] for i in range (F_list.shape[0])])

    # jika semua f dari F_list berubah tanda jika dievaluasi di tiap edge hypercube, maka ada akar di situ
    change_sign = np.array([np.any(product_combination[i]<0) for i in range (product_combination.shape[0])])
    if np.all(change_sign==True):
        # print(f'Ada akar di sini: \nX0={X0}')
        cluster.append(X0)

cluster = np.array(cluster)
print(f"Number of clusters containing root: {cluster.shape[0]}")

Number of clusters containing root: 12


In [17]:
# GA parameter
mutation = PolynomialMutation(prob=p_mutation)
algorithmGAp1 = GA(pop_size=n_point,eliminate_duplicates=True,mutation=mutation)

# termination variable
terminationp1 = DefaultSingleObjectiveTermination(
    xtol=1e-8,
    cvtol=1e-6,
    ftol=1e-6,
    period=20,
    n_max_gen=gen_max,
    n_max_evals=100000
)

def GenAl(n_var,n_obj,xl,xu,objective_function,algorithmGA,termination,seed=1,verbose=False):
    class myProblem(ElementwiseProblem):
        def __init__(self):
            super().__init__(n_var=n_var,n_obj=n_obj,xl=xl,xu=xu)
        def _evaluate(self, x, out, *args, **kwargs):
            out['F'] = -objective_function(x)

    problem = myProblem()
    result = minimize(problem=problem,
                    algorithm=algorithmGA,
                    termination=termination,
                    seed=seed,
                    verbose=verbose)
    return [result.X,result.F]

roots = []
values = []
for i in range (cluster.shape[0]):
    root,value = GenAl(2,1,xl=cluster[i,:,:][0],xu=cluster[i,:,:][-1],objective_function=root_objective_function,
                        algorithmGA=algorithmGAp1,termination=terminationp1,seed=0)
    roots.append(root)
    values.append(value)
roots = np.array(roots)
values = np.array(values)
print(f'Roots:\n{roots}\n\nValues: \n{values}')

Roots:
[[-6.43712573  0.15534876]
 [-6.2        -0.16104581]
 [-6.4         0.15618943]
 [-6.1170816  -0.16348884]
 [-1.          1.        ]
 [-0.93179264  1.06820304]
 [-0.15616774  6.4       ]
 [-0.15529     6.43981113]
 [ 0.16333465  6.12243972]
 [ 0.1610043   6.2       ]
 [ 0.59992547  0.76093895]
 [ 0.66761908  0.68959885]]

Values: 
[[-0.99996231]
 [-0.9257837 ]
 [-0.96344378]
 [-0.99982906]
 [-0.88079708]
 [-0.99934717]
 [-0.96057541]
 [-0.99989141]
 [-0.99997673]
 [-0.92947715]
 [-0.88749292]
 [-0.99901963]]


In [18]:
if dim == 1:
    list_criteria = [element for sublist in roots for element in sublist] #convert from 2D array into 1D array
else:
    list_criteria = roots
eligible_roots = np.array([x for x in list_criteria if (1-root_objective_function(x))<epsilon])
duplicated_roots = []
for i in range(len(eligible_roots)):
    for j in range (i+1,len(eligible_roots)):
        if np.linalg.norm(eligible_roots[i]-eligible_roots[j])<delta:
            duplicated_roots.append([eligible_roots[i],eligible_roots[j]])
duplicated_roots = np.unique(duplicated_roots,axis=0)

deselected_duplicated_roots = []
for i in range (len(duplicated_roots)):
    value_root_a = root_objective_function(duplicated_roots[i][0])
    value_root_b = root_objective_function(duplicated_roots[i][1])
    if dim == 1:
        if value_root_a>value_root_b:
            duplicated_root = duplicated_roots[i][1]
        else:
            duplicated_root = duplicated_roots[i][0]
    else:
        if value_root_a>value_root_b:
            duplicated_root = list(duplicated_roots[i][1])
        else:
            duplicated_root = list(duplicated_roots[i][0])
    deselected_duplicated_roots.append(duplicated_root)

if dim == 1:
    # Reshape the 1D array to have one column
    deselected_duplicated_roots = np.array(deselected_duplicated_roots).reshape(-1, 1)

    # Compare the 2D array with the reshaped 1D array
    exclude_condition = np.all(eligible_roots != deselected_duplicated_roots, axis=0)

    # Use the boolean mask to filter eligible_roots
    final_root = eligible_roots[exclude_condition]
else:
    if deselected_duplicated_roots:
        exclude_condition = np.all(eligible_roots != np.array(deselected_duplicated_roots)[:, np.newaxis], axis=2).all(axis=0)
        final_root = eligible_roots[exclude_condition]
    else:
        final_root = eligible_roots

print(f'Final Roots: \n{final_root}')

Final Roots: 
[[-6.43712573  0.15534876]
 [-6.1170816  -0.16348884]
 [-0.93179264  1.06820304]
 [-0.15529     6.43981113]
 [ 0.16333465  6.12243972]
 [ 0.66761908  0.68959885]]


### Automatic Function

In [1]:
# import genal_module as gam
# import numpy as np
# import matplotlib.pyplot as plt

# epsilon = 10**(-3)
# delta = 0.01
# n_point = 100
# gen_max = 300
# dim = 2
# p_mutation = 0.1

# # how many parts/slices do you desire in each dimension?
# parts = 100

# def objective_function(x):
#     f1 = np.exp(x[0]-x[1])-np.sin(x[0]+x[1])
#     f2 = (x[0]*x[1])**2-np.cos(x[0]+x[1])
#     return np.array([f1,f2])

# boundaries = np.array([(-10,10) for _ in range (dim)])

# gam.root_GenAl(objective_function=objective_function,
#                boundaries=boundaries,
#                dim=dim,
#                gen_max=gen_max,
#                n_points=n_point,
#                epsilon=epsilon,
#                delta=delta,
#                p_mutation=p_mutation,
#                parts=parts,
#                seed=0,
#                print_cluster=True)

Number of Clusters containing root: 12

Roots:
[[-6.43712573  0.15534876]
 [-6.2        -0.16104581]
 [-6.4         0.15618943]
 [-6.1170816  -0.16348884]
 [-1.          1.        ]
 [-0.93179264  1.06820304]
 [-0.15616774  6.4       ]
 [-0.15529     6.43981113]
 [ 0.16333465  6.12243972]
 [ 0.1610043   6.2       ]
 [ 0.59992547  0.76093895]
 [ 0.66761908  0.68959885]]

Values: 
[[-0.99996231]
 [-0.9257837 ]
 [-0.96344378]
 [-0.99982906]
 [-0.88079708]
 [-0.99934717]
 [-0.96057541]
 [-0.99989141]
 [-0.99997673]
 [-0.92947715]
 [-0.88749292]
 [-0.99901963]]


array([[-6.43712573,  0.15534876],
       [-6.1170816 , -0.16348884],
       [-0.93179264,  1.06820304],
       [-0.15529   ,  6.43981113],
       [ 0.16333465,  6.12243972],
       [ 0.66761908,  0.68959885]])